### ISSUE TITLE
Start developing the Home Page

### ISSUE THREAD

**Issue by amabelleS** [Bootcamp-Projects-Hamechina/hamechina#1]
- Get content to home page from hamechina
- Title: Home Page - Hamechina
- add links to discord server - explain each feature.

- later: feed for updates, meetups

**Comment by OliaKr** [comment]
היי, אשמח להרתם למשימה

**Comment by amabelleS** [comment]
מדהים:) משייכת גם אותה אליך. בגדול צריך שם התחלה בסיסית כרגע, לאסוף תכנים
ולהציג אותם.
העמוד הזה צריך עוד איפיון רציני, מאמינה שישתנה כל הזמן...

**Comment by amabelleS** [comment]
I'll soon close this issue and divide it to separate components for the home page
