### ISSUE TITLE
Homepage: HamechinaContentSection component

### ISSUE THREAD

**Issue by Drorka** [Bootcamp-Projects-Hamechina/hamechina#19]
Create the about the mechina section component (כל המידע על המכינה למציאת עבודה).
Path: app/(routes)/(homepage-sections)/_hamechina-content

Note that this component should display different content based on whether the user is logged in (a mechina member) or not.
Try and take that into account when building thi component, but feel free to also create the base, and leave this functionality for later.
 
See the Figma design: https://www.figma.com/file/Duqi7NP9cmnhVoQHJPyXGD/Hamechina?type=design&node-id=0%3A1&mode=design&t=9meolVcvbbpcYwRU-1

Link to component:

**Comment by SathvikKandadi** [comment]
Hey can you assign me this issue?

**Comment by amabelleS** [comment]
> Hey can you assign me this issue?

Hey @SathvikKandadi 🌞  Thank you very much, I assigned you another task for now. 
We will see if it will be open after:)

**Comment by Michal-Matayev** [comment]
Hi ,I will glad to do this issue :)

**Comment by amabelleS** [comment]
> Hi ,I will be glad to do this issue :)

Thx!

**Comment by amabelleS** [comment]
Added
