### ISSUE TITLE
Add the app logo as a favicon

### ISSUE THREAD

**Issue by amabelleS** [Bootcamp-Projects-Hamechina/hamechina#2]
- use it as a favicon
-  TODO: check if we can use hamechina logo

**Comment by amabelleS** [comment]
Here are some canva logo's:

![image](https://github.com/Bootcamp-Projects-Hamechina/hamechina/assets/45571546/d9c7ad7f-a62f-4cec-bcb5-34e7fae25c18)

![image](https://github.com/Bootcamp-Projects-Hamechina/hamechina/assets/45571546/0879558b-17b9-4321-9918-98719a73079f)

Next, we need to add one as a favicon

**Comment by OliaKr** [comment]
I'd like to work on that :)

**Comment by amabelleS** [comment]
- https://nextjs.org/learn/dashboard-app/adding-metadata: (2 ways:)
1. https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadata-object (```<link rel="icon" href="path/to/favicon.ico" />```)
2. 
<img width="756" alt="image" src="https://github.com/Bootcamp-Projects-Hamechina/hamechina/assets/45571546/4555360d-123a-4179-a1e3-632a20a311cb">

**Comment by amabelleS** [comment]
Updated:)
