### ISSUE TITLE
Add a README.md for the project

### ISSUE THREAD

**Issue by amabelleS** [Bootcamp-Projects-Hamechina/hamechina#3]
https://trello.com/c/0sopxkoZ

**Comment by OliaKr** [comment]
היי, אשמח לקחת את המשימה

**Comment by amabelleS** [comment]
היי אוליה,
שייכתי אליך את המשימה בגיטהאב. יש לי גם קצת לינקים של רידמי לדוגמא אם בא לך
שאשלח לך בשביל ההשראה:)
כל שאלה מוזמנת לפנות אלי, פה אם את רוצה תשובה יותר מהירה אפשרי גם בווצאפ.
הוספתי כבר מסמך של איך לתרום לקוד פתוח (
https://github.com/Bootcamp-Projects-Hamechina/hamechina/blob/main/CONTRIBUTING.md)
ויש גם בresources בטרלו קצת חומרים, ואם יש לך שאלות נוספות מוזמנת לפנות אלי.

תודה רבה!
אמאבל

**Comment by amabelleS** [comment]
PR merged, closing this issue:)

**Comment by amabelleS** [comment]
PR merged, closing this issue:)
