### ISSUE TITLE
Add Sign Up/In Page - FE

### ISSUE THREAD

**Issue by amabelleS** [Bootcamp-Projects-Hamechina/hamechina#6]
- Basic logic for authentication.
- UI element: input fields, bottoms.

https://trello.com/c/ziDdCZWl

**Comment by LinoyBu96** [comment]
I would like to take this mission.

**Comment by amabelleS** [comment]
maybe this would work for now, default next-auth config:

<img width="388" alt="image" src="https://github.com/Bootcamp-Projects-Hamechina/hamechina/assets/45571546/18fb14de-ef5c-4900-a2d4-97d50048d33b">
