### ISSUE TITLE
Design the home page

### ISSUE THREAD

**Issue by amabelleS** [Bootcamp-Projects-Hamechina/hamechina#9]
We need a basic design and content

https://trello.com/c/gu7Ef6W2

**Comment by Drorka** [comment]
assign me please (:

**Comment by amabelleS** [comment]
I'm closing this issue:)

https://www.figma.com/file/Duqi7NP9cmnhVoQHJPyXGD/Hamechina?type=design&node-id=0%3A1&mode=design&t=9meolVcvbbpcYwRU-1

**Comment by amabelleS** [comment]
Great job:)
